# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatStaGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatStaGram
    pod ‘Alamofire’, ‘~> 5.5’
    pod 'Kingfisher', '~> 7.0'
    pod 'SnapKit', '~> 5.6.0'
end
